image: Ubuntu2004  # образ для сборки

stack: node 19  # окружение

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - yarn install  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn run build   # команда сборки

test_script:
  - yarn run lint && yarn run test  # скрипт тестирования

deploy_script: # скрипт развёртывания
- git config --global credential.helper store
- git config --global user.name AppVeyor
- git config --global user.email ci@appveyor.com
- ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$GITHUB_TOKEN:x-oauth-basic@github.com`n" -NoNewline
- npx push-dir --dir=dist --branch=gh-pages --force --verbose


